services:
  - name: FlyjetAviatorBot
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: PORT
        value: 5000
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: starter  # Free ke jagah Starter ya Standard likho
