services:
  - name: FlyjetAviatorBot
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: PORT
        value: 5000
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 bot:app  # Flask ke liye sahi start command
    plan: starter
