services:
  - type: web    # Yeh line add karna mandatory hai
    name: FlyjetAviatorBot
    env: python   # Environment define karna jaroori hai
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: PORT
        value: 5000
